name: Pruebas y Publicación en GitHub Pages - Cobertura

on: 
  push:
    branches: 
      - main  
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Ejecutar pruebas y recolectar cobertura
      run: |
        cd ProyectoAsistencia/ProyectoAsistencia.Tests  
        dotnet test --collect:"XPlat Code Coverage"

        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:TestResults/**/coverage.cobertura.xml" "-targetdir:Reports/Cobertura" -reporttypes:HTML
      continue-on-error: true

    - name: Mover reportes de cobertura a carpeta
      run: |
        cd ProyectoAsistencia/ProyectoAsistencia.Tests

        # Crear carpeta temporal para los reportes
        mkdir -p ../../ReportesGH
        cp Reports/Cobertura/index.html ../../ReportesGH/ || echo "No coverage report found"
        cp Reports/Cobertura/report.css ../../ReportesGH/ || echo "No CSS for coverage report"

    - name: Verificar contenido de ReportesGH
      run: |
        ls -R ReportesGH || echo "ReportesGH is empty"

    - name: Publicar reportes de cobertura en GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Guardar carpeta ReportesGH temporalmente
        mv ReportesGH /tmp/ReportesGH

        # Configurar la rama gh-pages
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .  # Limpiar todo el contenido

        # Mover los reportes de cobertura a la raíz
        mv /tmp/ReportesGH/* .

        # Subir solo los reportes de cobertura
        git add .
        git commit -m "Actualizar reportes de cobertura" || echo "No hay cambios que confirmar"
        git push origin gh-pages --force
