name: "Snyk Analysis with Reports"

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x  

      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      - name: Restore and Build Project
        run: |
          cd ProyectoAsistencia
          dotnet restore
          dotnet build

      - name: Run Snyk Container Analysis
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd ProyectoAsistencia/ProyectoAsistencia.Tests
          snyk container test ProyectoAsistencia --json | snyk-to-html -o container-test-results.html

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ProyectoAsistencia/ProyectoAsistencia.Tests
          destination_dir: snyk-reports
